### ISSUE TITLE
Update Geographical Map example with selection of Equipments

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Molecule-Geographical-Position-Example#1]
With a light theme background, with english terms (or no terms).
From open map.

**Comment by Nyan11** [comment]
See : #3 

All icons come from : https://www.flaticon.com/authors/freepik (licence: https://www.freepikcompany.com/legal#nav-flaticon)
The map is a screen of openStreetMap. The licence require a citation see : https://www.openstreetmap.org/copyright


The licence require in both case a citation of the author.

I think we should put it in the readme.

**Comment by labordep** [comment]
Thanks @Nyan11, is this necessary to add openstreetmap licence on the view ?

**Comment by labordep** [comment]
I will do it.

**Comment by labordep** [comment]
Done in #6
