### ISSUE TITLE
Create a page on Molecule Geographical Position example on documentation

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Molecule-Geographical-Position-Example#2]
This page should contains the complete procedure to reproduce the example from scratch:
- Launcher
- Create image : Pharo 11
- Load molecule
- Execute example

**Comment by labordep** [comment]
Mettre à jour directement le fichier ReadMe. Si besoin prendre exemple sur le projet [ReuseTale](https://github.com/OpenSmock/ReuseTale)

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Molecule-Geographical-Position-Example/pull/5
